export interface Field {
    name: string;
    required: boolean;
    type: string;
    mask?: string;
    numOfOptions?: number;
    options?: {};
    value: string;
}

export interface Form {
  formId: string;
  formName: string;
  numOfFields?: number;
  startTime?: string;
  updateTime?: string;
}

export class FormClass {
  form = <Form> {
      formId: '',
      formName: '',
      numOfFields: 0,
      startTime: '',
      updateTime: ''
  };
}

export interface CustomOPtions {
  type: string
};

export class USStatesClass {
  usStates = <CustomOPtions> {
  option1 : "AL",   
  option2 : "AK",   
  option3 : "AS",   
  option4 : "AZ",   
  option5 : "AR",   
  option6 : "CA",   
  option7 : "CO",   
  option8 : "CT",   
  option9 : "DE",   
  option10: "DC",   
  option11: "FM",   
  option12: "FL",   
  option13: "GA",   
  option14: "GU",   
  option15: "HI",   
  option16: "ID",   
  option17: "IL",   
  option18: "IN",   
  option19: "IA",   
  option20: "KS",   
  option21: "KY",   
  option22: "LA",   
  option23: "ME",   
  option24: "MH",   
  option25: "MD",   
  option26: "MA",   
  option27: "MI",   
  option28: "MN",   
  option29: "MS",   
  option30: "MO",   
  option31: "MT",   
  option32: "NE",   
  option33: "NV",   
  option34: "NH",   
  option35: "NJ",   
  option36: "NM",   
  option37: "NY",   
  option38: "NC",   
  option39: "ND",   
  option40: "MP",   
  option41: "OH",   
  option42: "OK",   
  option43: "OR",   
  option44: "PW",   
  option45: "PA",   
  option46: "PR",   
  option47: "RI",   
  option48: "SC",   
  option49: "SD",   
  option50: "TN",   
  option51: "TX",   
  option52: "UT",   
  option53: "VT",   
  option54: "VI",   
  option55: "VA",   
  option56: "WA",   
  option57: "WV",   
  option58: "WI",   
  option59: "WY",
  type: "USStates"
  };
}

export class CountriesClass {
  countries = <CustomOPtions> {
    option1  :  "Afghanistan                                ",
    option2  :  "Albania                                    ",
    option3  :  "Algeria                                    ",
    option4  :  "Andorra                                    ",
    option5  :  "Angola                                     ",
    option6  :  "Anguilla                                   ",
    option7  :  "Antigua & Barbuda                          ",
    option8  :  "Argentina                                  ",
    option9  :  "Armenia                                    ",
    option10 :  "Australia                                  ",
    option11 :  "Austria                                    ",
    option12 :  "Azerbaijan                                 ",
    option13 :  "Bahamas                                    ",
    option14 :  "Bahrain                                    ",
    option15 :  "Bangladesh                                 ",
    option16 :  "Barbados                                   ",
    option17 :  "Belarus                                    ",
    option18 :  "Belgium                                    ",
    option19 :  "Belize                                     ",
    option20 :  "Benin                                      ",
    option21 :  "Bermuda                                    ",
    option22 :  "Bhutan                                     ",
    option23 :  "Bolivia                                    ",
    option24 :  "Bosnia & Herzegovina                       ",
    option25 :  "Botswana                                   ",
    option26 :  "Brazil                                     ",
    option27 :  "Brunei Darussalam                          ",
    option28 :  "Bulgaria                                   ",
    option29 :  "Burkina Faso                               ",
    option30 :  "Myanmar/Burma                              ",
    option31 :  "Burundi                                    ",
    option32 :  "Cambodia                                   ",
    option33 :  "Cameroon                                   ",
    option34 :  "Canada                                     ",
    option35 :  "Cape Verde                                 ",
    option36 :  "Cayman Islands                             ",
    option37 :  "Central African Republic                   ",
    option38 :  "Chad                                       ",
    option39 :  "Chile                                      ",
    option40 :  "China                                      ",
    option41 :  "Colombia                                   ",
    option42 :  "Comoros                                    ",
    option43 :  "Congo                                      ",
    option44 :  "Costa Rica                                 ",
    option45 :  "Croatia                                    ",
    option46 :  "Cuba                                       ",
    option47 :  "Cyprus                                     ",
    option48 :  "Czech Republic                             ",
    option49 :  "Democratic Republic of the Congo           ",
    option50 :  "Denmark                                    ",
    option51 :  "Djibouti                                   ",
    option52 :  "Dominican Republic                         ",
    option53 :  "Dominica                                   ",
    option54 :  "Ecuador                                    ",
    option55 :  "Egypt                                      ",
    option56 :  "El Salvador                                ",
    option57 :  "Equatorial Guinea                          ",
    option58 :  "Eritrea                                    ",
    option59 :  "Estonia                                    ",
    option60 :  "Ethiopia                                   ",
    option61 :  "Fiji                                       ",
    option62 :  "Finland                                    ",
    option63 :  "France                                     ",
    option64 :  "French Guiana                              ",
    option65 :  "Gabon                                      ",
    option66 :  "Gambia                                     ",
    option67 :  "Georgia                                    ",
    option68 :  "Germany                                    ",
    option69 :  "Ghana                                      ",
    option70 :  "Great Britain                              ",
    option71 :  "Greece                                     ",
    option72 :  "Grenada                                    ",
    option73 :  "Guadeloupe                                 ",
    option74 :  "Guatemala                                  ",
    option75 :  "Guinea                                     ",
    option76 :  "Guinea-Bissau                              ",
    option77 :  "Guyana                                     ",
    option78 :  "Haiti                                      ",
    option79 :  "Honduras                                   ",
    option80 :  "Hungary                                    ",
    option81 :  "Iceland                                    ",
    option82 :  "India                                      ",
    option83 :  "Indonesia                                  ",
    option84 :  "Iran                                       ",
    option85 :  "Iraq                                       ",
    option86 :  "Israel and the Occupied Territories        ",
    option87 :  "Italy                                      ",
    option88 :  "Ivory Coast (Cote d'Ivoire)                ",
    option89 :  "Jamaica                                    ",
    option90 :  "Japan                                      ",
    option91 :  "Jordan                                     ",
    option92 :  "Kazakhstan                                 ",
    option93 :  "Kenya                                      ",
    option94 :  "Kosovo                                     ",
    option95 :  "Kuwait                                     ",
    option96 :  "Kyrgyz Republic (Kyrgyzstan)               ",
    option97 :  "Laos                                       ",
    option98 :  "Latvia                                     ",
    option99 :  "Lebanon                                    ",
    option100:  "Lesotho                                    ",
    option101:  "Liberia                                    ",
    option102:  "Libya                                      ",
    option103:  "Liechtenstein                              ",
    option104:  "Lithuania                                  ",
    option105:  "Luxembourg                                 ",
    option106:  "Republic of Macedonia                      ",
    option107:  "Madagascar                                 ",
    option108:  "Malawi                                     ",
    option109:  "Malaysia                                   ",
    option110:  "Maldives                                   ",
    option111:  "Mali                                       ",
    option112:  "Malta                                      ",
    option113:  "Martinique                                 ",
    option114:  "Mauritania                                 ",
    option115:  "Mauritius                                  ",
    option116:  "Mayotte                                    ",
    option117:  "Mexico                                     ",
    option118:  "Moldova, Republic of                       ",
    option119:  "Monaco                                     ",
    option120:  "Mongolia                                   ",
    option121:  "Montenegro                                 ",
    option122:  "Montserrat                                 ",
    option123:  "Morocco                                    ",
    option124:  "Mozambique                                 ",
    option125:  "Namibia                                    ",
    option126:  "Nepal                                      ",
    option127:  "Netherlands                                ",
    option128:  "New Zealand                                ",
    option129:  "Nicaragua                                  ",
    option130:  "Niger                                      ",
    option131:  "Nigeria                                    ",
    option132:  "Korea, Democratic Republic of (North Korea)",
    option133:  "Norway                                     ",
    option134:  "Oman                                       ",
    option135:  "Pacific Islands                            ",
    option136:  "Pakistan                                   ",
    option137:  "Panama                                     ",
    option138:  "Papua New Guinea                           ",
    option139:  "Paraguay                                   ",
    option140:  "Peru                                       ",
    option141:  "Philippines                                ",
    option142:  "Poland                                     ",
    option143:  "Portugal                                   ",
    option144:  "Puerto Rico                                ",
    option145:  "Qatar                                      ",
    option146:  "Reunion                                    ",
    option147:  "Romania                                    ",
    option148:  "Russian Federation                         ",
    option149:  "Rwanda                                     ",
    option150:  "Saint Kitts and Nevis                      ",
    option151:  "Saint Lucia                                ",
    option152:  "Saint Vincent's & Grenadines               ",
    option153:  "Samoa                                      ",
    option154:  "Sao Tome and Principe                      ",
    option155:  "Saudi Arabia                               ",
    option156:  "Senegal                                    ",
    option157:  "Serbia                                     ",
    option158:  "Seychelles                                 ",
    option159:  "Sierra Leone                               ",
    option160:  "Singapore                                  ",
    option161:  "Slovak Republic (Slovakia)                 ",
    option162:  "Slovenia                                   ",
    option163:  "Solomon Islands                            ",
    option164:  "Somalia                                    ",
    option165:  "South Africa                               ",
    option166:  "Korea, Republic of (South Korea)           ",
    option167:  "South Sudan                                ",
    option168:  "Spain                                      ",
    option169:  "Sri Lanka                                  ",
    option170:  "Sudan                                      ",
    option171:  "Suriname                                   ",
    option172:  "Swaziland                                  ",
    option173:  "Sweden                                     ",
    option174:  "Switzerland                                ",
    option175:  "Syria                                      ",
    option176:  "Tajikistan                                 ",
    option177:  "Tanzania                                   ",
    option178:  "Thailand                                   ",
    option179:  "Timor Leste                                ",
    option180:  "Togo                                       ",
    option181:  "Trinidad & Tobago                          ",
    option182:  "Tunisia                                    ",
    option183:  "Turkey                                     ",
    option184:  "Turkmenistan                               ",
    option185:  "Turks & Caicos Islands                     ",
    option186:  "Uganda                                     ",
    option187:  "Ukraine                                    ",
    option188:  "United Arab Emirates                       ",
    option189:  "United States of America (USA)             ",
    option190:  "Uruguay                                    ",
    option191:  "Uzbekistan                                 ",
    option192:  "Venezuela                                  ",
    option193:  "Vietnam                                    ",
    option194:  "Virgin Islands (UK)                        ",
    option195:  "Virgin Islands (US)                        ",
    option196:  "Yemen                                      ",
    option197:  "Zambia                                     ",
    option198:  "Zimbabwe                                   ",
    type: "Countries"
  };
}